#define PI 3.14159265

#define MAX_SHAPES 100
#define MAX_VERTICES_PER_SHAPE 10000
#define NUMBER_OF_HOMOGENEOUS_COORDS 4
#define MAX_CONNECTIONS_PER_VERTEX 4

#define MAXVERTICES MAX_SHAPES * MAX_VERTICES_PER_SHAPE

#define SCREENWIDTH 3000
#define SCREENHEIGHT 2000

// Field of View in degrees
#define fov 45.0